config/routes.rb
Stylish::Engine.routes.draw do
  resources :images
  resources :styles do
    get :enable, on: :collection
  end

  root to: 'application#index'
end

app/models/stylish/image.rb
module Stylish
  class Image < ActiveRecord::Base
    CATEGORIES = [1,2]
    CONTENT_TYPES = /\Aimage/.freeze

    attr_accessor :act

    attr_accessible :name, :description, :data, :active, :default, :category

    validates :name, :data, presence: true

    has_attached_file :data, validate_media_type: true #, styles: { thumb: 'x150', croppable: '600x600>' }
    validates_attachment_content_type :data, content_type: CONTENT_TYPES

    before_validation :set_defaults

    def self.categories
      CATEGORIES
    end

    private

    def set_defaults
      self.active = false if active.nil?
      self.default = false if default.nil?
    end
  end
end

app/models/stylish/style.rb
module Stylish
  class Style < ActiveRecord::Base
    CATEGORIES = [1,2]
    attr_accessible :name, :description, :data, :active, :default, :category

    validates :name, uniqueness: true
    validates :name, presence: true
    validates :data, presence: true

    def self.categories
      CATEGORIES
    end
  end
end

app/controllers/stylish/application_controller.rb
require_dependency 'stylish/service_factory'

module Stylish
  class ApplicationController < ActionController::Base
    layout 'stylish/layouts/application'
  end
end

app/controllers/stylish/concerns/common_behavior.rb
module Stylish
  module CommonBehavior
    extend ActiveSupport::Concern

    included do
      before_filter :find_object, only: [:edit, :update, :destroy]
      before_filter :new_object, only: [:new, :create]

      def index
        instance_variable_set("@#{controller_name}", object_class.all)
      end

      def new; end

      def create
        respond_to do |format|
          if object.save
            format.html { redirect_to controller: controller_name, action: :index }
            format.json { render head: :ok }
          else
            format.html { render :new }
            format.json { render json: object.errors }
          end
        end
      end

      def edit; end

      def update
        service = Stylish::ServiceFactory.instance.get(object_params[:act].to_sym, object, object_params)
        if service.call
          flash[:info] = 'cool'
        else
          flash[:error] = object.errors.full_messages.join(', ')
        end

        redirect_to action: :index
      end

      def destroy
        respond_to do |format|
          if object.destroy
            format.html { redirect_to controller: controller_name, action: :index }
            format.json { render head: :ok }
          else
            format.html { redirect_to controller: controller_name, action: :index }
            format.json { render json: object.errors }
          end
        end
      end

      private

      def object
        instance_variable_get("@#{controller_name.singularize}")
      end

      def set_object(value)
        instance_variable_set("@#{controller_name.singularize}", value)
      end

      def find_object
        set_object(object_class.find(params[:id]))
      end

      def new_object
        set_object(object_class.new(object_params))
      end

      def object_params
        params.fetch(controller_name.singularize.to_sym, {})
      end

      def object_class
        Stylish::ModelFactory.instance.get_class(controller_name)
      end
    end
  end
end

app/controllers/stylish/images_controller.rb
require_dependency 'stylish/application_controller'

module Stylish
  class ImagesController < ApplicationController
    include Stylish::CommonBehavior
  end
end

app/controllers/stylish/styles_controller.rb
require_dependency 'stylish/application_controller'

module Stylish
  class StylesController < ApplicationController
    include Stylish::CommonBehavior

    def enable
      session[:style_editor] = params[:enable].present?
      redirect_to styles_path
    end
  end
end

app/helpers/stylish/styles_helper.rb
module Stylish
  module StylesHelper
    def enable_editor_link
      if session[:style_editor].present?
        link_to 'Disable editor', enable_styles_path, class: 'btn btn-warning'
      else
        link_to 'Enable editor', enable_styles_path(enable: true), class: 'btn btn-warning'
      end
    end
  end
end

app/views/stylish/images/_form.haml
.col-md-6
  = form_for @image, multipart: true do |f|
    - if f.object.class.categories
      .form-group
        = f.select :category, f.object.class.categories, prompt: 'Without category', class: 'form-control'
    .form-group
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.text_area :description, class: 'form-control'
    .form-group
      = f.file_field :data, class: 'form-control'
    .form-group
      = f.submit 'Save', class: 'btn btn-default'

app/views/stylish/images/_image.haml
.image
  .form-group
    %label Name
    = image.name
  .form-group
    %label Name
    = image.description
  .form-group
    = image_tag(image.data)
  .form-group
    %label Category
    = image.category
  .form-group
    - if image.active?
      active
    - else
      = form_for image do |f|
        = f.hidden_field :act, value: 'active'
        = f.hidden_field :active, value: '1'
        = f.submit 'Activate'

  .form-group
    - if image.default?
      default
    - else
      = form_for image do |f|
        = f.hidden_field :act, value: 'default'
        = f.hidden_field :default, value: '1'
        = f.submit 'Make default'

  .form-group
    = link_to 'Delete', image, data: { confirm: 'Are you sure?' }, method: :delete

app/views/stylish/images/index.haml
= link_to 'New Image', new_image_path, class: 'btn btn-success'

= render @images

app/views/stylish/images/new.haml
= render 'form'

app/views/stylish/layouts/application.haml
%html
  %head
  %title Stylish
  = stylesheet_link_tag 'stylish/application', media: :all
  = javascript_include_tag 'stylish/application'
  = csrf_meta_tags
  %body
    .stylish.container-fluid#main-container
      %ul.nav.nav-tabs{ role: 'tablist' }
        %li
          = link_to 'Images', images_path
        %li
          = link_to 'Styles', styles_path
      .tab-content
        #flash
          = render 'stylish/shared/messages'
        = yield

app/views/stylish/shared/_messages.html.haml
.row
  - flash.each do |type, value|
    - next if value.blank?

    .col-md-8.alert.alert-dismissible{ class: "alert-#{type} ", role: :alert }
      %a{ href: '#', class: 'close', data: { dismiss: 'alert' }, aria: { label: 'close' } }
        &times;
      %strong
        = value

app/views/stylish/styles/_form.haml
.col-md-6
  = form_for @style do |f|
    - if f.object.class.categories
      .form-group
        = f.select :category, f.object.class.categories, prompt: 'Without category', class: 'form-control'
    .form-group
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.text_area :description, class: 'form-control'
    .form-group
      = f.text_area :data, class: 'form-control'
    .form-group
      = f.submit 'Save', class: 'btn btn-default'

app/views/stylish/styles/_style.haml
.image
  .form-group
    %label Name
    = style.name
  .form-group
    %label Name
    = style.description
  .form-group
    %label Data
    = style.data
  .form-group
    %label Category
    = style.category
  .form-group
    - if style.active?
      active
    - else
      = form_for style do |f|
        = f.hidden_field :act, value: 'active'
        = f.hidden_field :active, value: '1'
        = f.submit 'Activate'

  .form-group
    - if style.default?
      default
    - else
      = form_for style do |f|
        = f.hidden_field :act, value: 'default'
        = f.hidden_field :default, value: '1'
        = f.submit 'Make default'

  .form-group
    = link_to 'Delete', style, data: { confirm: 'Are you sure?' }, method: :delete

app/views/stylish/styles/index.haml
= link_to 'New style', new_style_path, class: 'btn btn-success'
= enable_editor_link

= render @styles

app/views/stylish/styles/new.haml
= render 'form'